const images = {
  Tomato: require('./assets/images/tomato.jpg'),
  Onion: require('./assets/images/onion.jpg'),
  Cucumber: require('./assets/images/cucumber.jpg'),
  Brocolli: require('./assets/images/brocolli.jpg'),
  Bell_Pepper: require('./assets/images/bell_pepper.jpg'),
  Chili: require('./assets/images/chili.jpg'),
  Celery: require('./assets/images/celery.jpg'),
  Potato: require('./assets/images/potato.jpg'),
  Orange: require('./assets/images/orange.jpg'),
  Apple: require('./assets/images/apple.jpg'),
  Pear: require('./assets/images/pear.jpg'),
  Watermelon: require('./assets/images/watermelon.jpg'),
  Plum: require('./assets/images/plum.jpg'),
  Lemon: require('./assets/images/lemon.jpg'),
  Peach: require('./assets/images/peach.jpg'),
  Cherry: require('./assets/images/cherry.jpg'),
  Grapes: require('./assets/images/grapes.jpg'),
  Crab: require('./assets/images/crab.jpg'),
  Shrimp: require('./assets/images/shrimp.jpg'),
  Lobster: require('./assets/images/lobster.jpg'),
  Oyster: require('./assets/images/oyster.jpg'),
  Squid: require('./assets/images/squid.jpg'),
  Bass: require('./assets/images/bass.jpg'),
  Salmon: require('./assets/images/salmon.jpg'),
  Tuna: require('./assets/images/tuna.jpg'),
  Lamb_Chop: require('./assets/images/lamb_chop.jpg'),
  Sirloin: require('./assets/images/sirloin.jpg'),
  Dice_Beef: require('./assets/images/dice_beef.jpg'),
  Chicken: require('./assets/images/chicken.jpg'),
  Salami: require('./assets/images/salami.jpg'),
  Sausages: require('./assets/images/sausages.jpg'),
};

export default images;